//
// Generated file, do not edit! Created by opp_msgc 4.1 from applications/pithos/Message.msg.
//

#ifndef _MESSAGE_M_H_
#define _MESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>applications/pithos/Message.msg</tt> by opp_msgc.
 * <pre>
 * enum MessageTypes
 * {
 *     STORE_REQ = 1;
 * };
 * </pre>
 */
enum MessageTypes {
    STORE_REQ = 1
};

/**
 * Class generated from <tt>applications/pithos/Message.msg</tt> by opp_msgc.
 * <pre>
 * message Message {
 *     int64_t value;
 *     int payloadType enum(MessageTypes);
 * }
 * </pre>
 */
class Message : public ::cMessage
{
  protected:
    int64_t value_var;
    int payloadType_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Message&);

  public:
    Message(const char *name=NULL, int kind=0);
    Message(const Message& other);
    virtual ~Message();
    Message& operator=(const Message& other);
    virtual Message *dup() const {return new Message(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int64_t getValue() const;
    virtual void setValue(int64_t value_var);
    virtual int getPayloadType() const;
    virtual void setPayloadType(int payloadType_var);
};

inline void doPacking(cCommBuffer *b, Message& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Message& obj) {obj.parsimUnpack(b);}


#endif // _MESSAGE_M_H_
